"""add new fields for gpt function params model

Revision ID: a1ea50e7310c
Revises: d67f336efaa0
Create Date: 2024-05-11 22:19:27.267872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ea50e7310c'
down_revision: Union[str, None] = 'd67f336efaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function_parameters', sa.Column('description', sa.String(), nullable=False))
    op.add_column('function_parameters', sa.Column('required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function_parameters', 'required')
    op.drop_column('function_parameters', 'description')
    # ### end Alembic commands ###
