"""create table for gpt function parameters

Revision ID: d67f336efaa0
Revises: bb693e215633
Create Date: 2024-05-11 18:27:50.913064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67f336efaa0'
down_revision: Union[str, None] = 'bb693e215633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('function_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('function_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('param_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['gpt_functions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('function_parameters')
    # ### end Alembic commands ###
